// var deck = ["2clubs","3clubs","4clubs","5clubs","6clubs","7clubs","8clubs","9clubs","10clubs",
// "knightclubs","queenclubs","kingclubs","aceclubs","2diamonds","3diamonds","4diamonds",
// "5diamonds","6diamonds","7diamonds","8diamonds","9diamonds","10diamonds",
// "knightdiamonds","queendiamonds","kingdiamonds","acediamonds","2hearts","3hearts",
// "4hearts","5hearts","6hearts","7hearts","8hearts","9hearts","10hearts","knighthearts",
// "queenhearts","kinghearts","acehearts","2spades","3spades","4spades","5spades",
// "6spades","7spades","8spades","9spades","10spades","knightspades","queenspades",
// "kingspades","acespades"];
var deck = [{type: "clubs", number: "ace", src: "img/clubs/aceClubs.jpg", id: "aceClubs"},
{type: "clubs", number: "two", src: "img/clubs/twoClubs.jpg", id: "twoClubs"},
{type: "clubs", number: "three", src: "img/clubs/threeClubs.jpg", id: "threeClubs"},
{type: "clubs", number: "four", src: "img/clubs/fourClubs.jpg", id: "fourClubs"},
{type: "clubs", number: "five", src: "img/clubs/fiveClubs.jpg", id: "fiveClubs"},
{type: "clubs", number: "six", src: "img/clubs/sixClubs.jpg", id: "sixClubs"},
{type: "clubs", number: "seven", src: "img/clubs/sevenClubs.jpg", id: "sevenClubs"},
{type: "clubs", number: "eight", src: "img/clubs/eightClubs.jpg", id: "eightClubs"},
{type: "clubs", number: "nine", src: "img/clubs/nineClubs.jpg", id: "nineClubs"},
{type: "clubs", number: "ten", src: "img/clubs/tenClubs.jpg", id: "tenClubs"},
{type: "clubs", number: "jack", src: "img/clubs/jackClubs.jpg", id: "jackClubs"},
{type: "clubs", number: "queen", src: "img/clubs/queenClubs.jpg", id: "queenClubs"},
{type: "clubs", number: "king", src: "img/clubs/kingClubs.jpg", id: "kingClubs"},
{type: "diamonds", number: "ace", src: "img/diamonds/ace.jpg", id: "aceDiamonds"},
{type: "diamonds", number: "two", src: "img/diamonds/twoDiamonds.jpg", id: "twoDiamonds"},
{type: "diamonds", number: "three", src: "img/diamonds/threeDiamonds.jpg", id: "threeDiamonds"},
{type: "diamonds", number: "four", src: "img/diamonds/fourDiamonds.jpg", id: "fourDiamonds"},
{type: "diamonds", number: "five", src: "img/diamonds/fiveDiamonds.jpg", id: "fiveDiamonds"},
{type: "diamonds", number: "six", src: "img/diamonds/sixDiamonds.jpg", id: "sixDiamonds"},
{type: "diamonds", number: "seven", src: "img/diamonds/sevenDiamonds.jpg", id: "sevenDiamonds"},
{type: "diamonds", number: "eight", src: "img/diamonds/eightDiamonds.jpg", id: "eightDiamonds"},
{type: "diamonds", number: "nine", src: "img/diamonds/nineDiamonds.jpg", id: "nineDiamonds"},
{type: "diamonds", number: "ten", src: "img/diamonds/tenDiamonds.jpg", id: "tenDiamonds"},
{type: "diamonds", number: "jack", src: "img/diamonds/jackDiamonds.jpg", id: "jackDiamonds"},
{type: "diamonds", number: "queen", src: "img/diamonds/queenDiamonds.jpg", id: "queenDiamonds"},
{type: "diamonds", number: "king", src: "img/diamonds/kingDiamonds.jpg", id: "kingDiamonds"},



];
